export let departmentData=["Doctor Of Medicine",
"Paramedics",
"Radiologic Technology",
"Medical Laboratory Sciences",
"Public Health",
"Chemical Engineering",
"Civil Engineering",
"Electrical Engineering",
"Mechanical Engineering",
"Biomedical Engineering",
"Industrial Engineering",
"Pharmacy",
"Doctor Of Pharmacy(Pharm D.)",
"Nursing",
"Midwifery",
"Dental Surgery",
"Dental Technology",
"Allied Dental Sciences",
"Animal Production",
"Plant Production",
"Nutrition & Food Technology",
"Veterinary Medicine And Surgery",
"Natural Resources & Environment",
"Aeronautical Engineering",
"Arabic Language",
"English Language & Linguistics",
"Humanities",
"Military",
"Mathematics",
"Chemistry",
"Physics",
"Applied Biological Sciences",
"Biotechnology & Genetic Engineering",
"Optometry",
"Physical Therapy",
"Occupational Therapy",
"Audiology & Speech Pathology",
"Clinical Rehabilitation Science",
"Nanotechnology And Engineering 1",
"Nanotechnology And Engineering 2",
"Health Managment And Policy",
"Computer Engineering",
"Computer Science",
"Computer Information Systems",
"Network Engineering And Security",
"Software Engineering",
"Urban Planning & Studies",
"Nuclear Engineering",
"Architecture",
"City Planning And Design",
"Design And Visual Communication",
"Language Center"].sort()